### ISSUE TITLE
Safari bug for `el` heigh calculation in combination with `height fill`

### ISSUE THREAD

**Issue by jhf** [mdgriffith/elm-ui#147]
I've stumbled upon a bug in Elm-ui 1.1.5, that was not present in 1.1.0.
The SSCCE is [here](https://ellie-app.com/6zRKyKKKM2La1)
The problem appears to be that the height of the first `el` is 0, and therefore the second
text is rendered on the first.
![image](https://user-images.githubusercontent.com/18099/64458515-d627ac80-d0f5-11e9-90cc-4d216a0bf620.png)

**Expected behavior**
The texts do not render on top of each other,  as shown here:
![image](https://user-images.githubusercontent.com/18099/64458452-a8dafe80-d0f5-11e9-9e55-3ed5bfb83849.png)

**Versions**
 - OS: macOS Mojave 10.14.5
 - Browser: Safari
 - Browser Version: 12.1.1 (14607.2.6.1.1)
 - Elm Version: 0.19
 - Elm UI Version: 1.1.5

**Comment by cjlucas** [comment]
Summarizing this [Slack conversation](https://elmlang.slack.com/archives/C4F9NBLR1/p1567719428112700):

Going from the SSCCE @jhf put up, we were able to determine that the only difference in the computed CSS was the following declaration:

```css
.s.c > .s {
    flex-basis: 0%;
}
```

Which may relate to https://github.com/philipwalton/flexbugs#flexbug-1, although that bug is quite old and has been fixed in major browsers years ago. The suggestion link is to use `flex-basis: auto; flex-shrink: 0` as a work around.

I was able to pinpoint the issue to this https://github.com/mdgriffith/elm-ui/commit/fd08f1a953484ba96f2d05037d4f208eab351514 commit, which lines up.

I was able to apply the workaround successfully to the linked SSCCE, which you can find here: https://ellie-app.com/6BhxMsrcMCZa1

I don't have any suggestions for a proper fix as I'm not very experienced with flex box, but I hope this helps!

**Comment by alexkorban** [comment]
#bug #has-ellie

**Comment by lucamug** [comment]
#has-test
