### ISSUE TITLE
Consider renaming `el` to `element`

### ISSUE THREAD

**Issue by salutis** [mdgriffith/elm-ui#21]
There are various terms in design that start with `el`, e.g. the `ellipse` element in SVG, "elevation" in Material Design, etc. All the other functions and types in `elm-ui` are clear at the point of use. In the spirit of the "clarity over brevity" rule (borrowed from Swift API Guidelines), I suggest to rename the `el` element to `element` or something similar.

**Comment by lsunsi** [comment]
@salutis I see your point in this, since there aren't any other abbreviations. That said, I feel like the API design considered the `el` method as a special one that would be used everywhere, and that's why they went with terseness here.

I'm not saying I agree, just pointing out what I imagine was the intent. When I'm using this lib I usually import Element as El as well, so I'm using `El.el` all over the place haha :p

**Comment by mdgriffith** [comment]
I appreciate the suggestion and Lucas is basically on track with why I went this direction.

I generally agree with clarity over brevity, though I haven't had anyone mention confusion over the naming of `el`, so I'm not sure there is a pain point here.  If we add an `ellipse` or an `elevation`, we definitely won't shorten those :)
