### ISSUE TITLE
Reason behind the elm-ui name?

### ISSUE THREAD

**Issue by AlmightyFloppyFish** [mdgriffith/elm-ui#27]
There's already a library for elm [called elm-ui](https://github.com/gdotdesign/elm-ui) that has over 700 stars, this makes it very confusing as google picks up that library over yours. Why would you use a name that's already taken?

**Comment by mdgriffith** [comment]
I mention it here in the announcement post on discourse: https://discourse.elm-lang.org/t/a-new-release-and-renaming-style-elements-to-elm-ui/1821

That project hasn't been active in a long time and would have a tough time updating to Elm 0.19 due to it's use of native code.  The author has also moved on from the Elm community to start his own language.  So, in that sense the name isn't really taken because it's not in active use.
