### ISSUE TITLE
Input.text crops bottom of long tail letters

### ISSUE THREAD

**Issue by joecorkerton** [mdgriffith/elm-ui#64]
Example: https://ellie-app.com/3N8ng5WKqqna1

<img width="526" alt="screenshot 2018-11-03 at 15 58 08" src="https://user-images.githubusercontent.com/20556001/47954526-d1004b00-df82-11e8-86a6-310bf8bacfa5.png">

Long tail letters like 'y', 'p' etc have the bottoms cropped off in the input.text field.  It is more significant with certain fonts.

It doesn't happen with placeholder text, only the input text itself

**Expected behavior**
The letters typed in the input are rendered correctly

**Versions**
 - OS: Macos Mojave
 - Browser Chrome
 - Browser Version 70.0
 - Elm Version 0.19
 - Elm UI Version 1.1.0

**Comment by z5h** [comment]
I cannot reproduce this on:
Safari, Firefox OR Chrome (Version 70.0.3538.77 (Official Build) (64-bit)).

**Comment by bburdette** [comment]
It renders correctly for me on Chromium Version 69.0.3497.100 (Developer Build) (64-bit) and on Firefox 62.0.3.  I was unable to change the text by typing so I made a new ellie for that:
https://ellie-app.com/3QQCsKhrGM3a1

**Comment by z5h** [comment]
@joecorkerton , have you disabled all plugins and custom configurations? 
I tested in a fresh install of the same version and had no problems. (I'm also on Macos Mojave)

**Comment by joecorkerton** [comment]
I tried disabling all extensions and it still shows up. If no one else is able to reproduce then it must be just an issue with my setup

**Comment by auxsoft** [comment]
I can reproduce it on Windows.

Windows 7
Chrome 70.0.3538.102

![image](https://user-images.githubusercontent.com/2872204/48314228-3e286780-e5a5-11e8-852a-cc2f4c49934e.png)

The problem is that the line-height of 1.05 used for inputs is too little. As mentioned in the comments in the code the normal is more like 1.2. I think Normalize.css, for example, uses 1.15.

Note that it's too small even for Firefox. It's just that Firefox renders it differently and allows the part outside the input to show through. But if you remove the padding, the problem manifests.

The input in Firefox without the padding:
![image](https://user-images.githubusercontent.com/2872204/48314263-df172280-e5a5-11e8-8b7c-786b6835b3d5.png)

**Comment by lucamug** [comment]
I experienced this issue in Android and I fixed using this workaround in the input field:

    htmlAttribute <| Html.Attributes.style "line-height" "1.2"
