### ISSUE TITLE
No select field implementation?

### ISSUE THREAD

**Issue by jesse-c** [mdgriffith/elm-ui#76]
I'm surprised there wasn't already an issue for this (unless I missed it!), but, I was wondering about why the `select` element hasn't been implemented?

**Comment by r1sc** [comment]
Read this: https://github.com/mdgriffith/elm-ui/blob/master/CHANGES-FROM-STYLE-ELEMENTS.md - along the bottom of the page there is an explanation.

However as stated, you can still just ```html (select...)```

**Comment by jesse-c** [comment]
> Input.select has been removed. Ultimately this came down to it being recommended against for most UX purposes.

Wow, okay.

Thanks!

**Comment by danstn** [comment]
@jesse-c  @mdgriffith 

Just out of curiosity - what exactly does
> ...recommended against for most UX purposes."

 mean?

Is there an elaboration on it somewhere? Even if it's "bad UX" - how much does it hurt having it as part of Elm-UI?

We're building an internal UI library 100% based on Style Elements and are making the switch to Elm-UI now (mostly because of the simplified api for styling and Element.Lazy). Kinda need select as you could imagine some web apps still use it. Building one of the core elements in raw html and losing the all the awesomeness of Elm-UI is...sad.

**Comment by absynce** [comment]
The link to the explanation doesn't work anymore. Here's one that does: https://github.com/mdgriffith/elm-ui/blob/1.0.0/CHANGES-FROM-STYLE-ELEMENTS.md#input.

I like that it goes into a more-detailed explanation:
> If you're looking for a replacement, consider any of these options which will likely create a better experience:
> - Input.checkbox
> - Input.radio/Input.radioRow with custom styling
> - Input.text with some sort of suggestion/autocomplete attached to it.
